theme: minima

title: Michael Podboreski's Blog
author: Michael Podboreski
email: m.podboreski@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Michael Podboreski's Dev Blog on GitHub is a documentation of the more personal side of my learning journey.

# social links
# twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  mpodboreski

show_excerpts: true # set to false to remove excerpts on the homepage
